[package]
name = "Gravity"
version = "0.0.4"
edition = "2024"

[dependencies]
iced = { version = "0.14.0", features = ["highlighter"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.149"
image = "0.24"
directories = "5.0"
rfd = "0.15"
iced_term = "0.7.0"

[package.metadata.bundle]
name = "Gravity Editor"
icon = ["appicon.icns"]
version = "1.0.0"
category = "Productivity"
long_description = """
MacOS Test Release
"""